language: python
python:
  - 3.6
before_install:
  - sqlite3 --version
  - sudo apt-get install -y sqlite3
  - sqlite3 --version
install:
  - pip install -r requirements.txt
script:
  - python manage.py test polls
