dist: xenial
language: python
python:
  - 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3
install:
  - pip install -r requirements.txt
script:
  - python manage.py test polls
